### ISSUE TITLE
"Error: Could not load the "sharp" module using the win32-arm64 runtime"

### ISSUE THREAD

**Issue by wojtekmaj** [lovell/sharp-libvips#238]
## Possible install-time or require-time problem

- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?

- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?

- [ ] I am using npm >= 9.6.5 with `--include=optional`
- [x] I am using yarn >= 3.2.0
- [ ] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete error message, including the full stack trace?

```
node_modules\sharp\lib\sharp.js:114
  throw new Error(help.join('\n'));
        ^

Error: Could not load the "sharp" module using the win32-arm64 runtime
Possible solutions:
- Manually install libvips >= 8.15.2
- Add experimental WebAssembly-based dependencies:
    npm install --cpu=wasm32 sharp
    npm install @img/sharp-wasm32
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (node_modules\sharp\lib\sharp.js:114:9)
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1091:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)
    at Module.require (node:internal/modules/cjs/loader:1297:12)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (node_modules\sharp\lib\constructor.js:10:1) 
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
```

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

npm verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
npm info using npm@10.8.1
npm info using node@v22.3.0
npm verbose title npm install sharp
npm verbose argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verbose logfile logs-max:10 dir:C:\Users\wojte\AppData\Local\npm-cache\_logs\2024-06-25T13_33_42_309Z-
npm verbose logfile C:\Users\wojte\AppData\Local\npm-cache\_logs\2024-06-25T13_33_42_309Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 338ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color 126ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/semver 233ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm 270ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-arm64 157ms (cache miss)     
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 296ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-x64 300ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-arm64 326ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm 139ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-s390x 142ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-x64 141ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm64 183ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-arm64 147ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-x64 152ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-ia32 130ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-wasm32 138ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-x64 124ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-x64 736ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-s390x 740ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-x64 768ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm64 779ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-arm64 790ms (cache miss)        
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-x64 610ms (cache miss)       
npm http fetch GET 200 https://registry.npmjs.org/color-convert 101ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@emnapi%2fruntime 144ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-string 599ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/tslib 85ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 87ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-name 97ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color-name 576ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 106ms (cache miss)
npm verbose reify failed optional dependency node_modules\@img\sharp-win32-x64
npm verbose reify failed optional dependency node_modules\@img\sharp-win32-ia32
npm verbose reify failed optional dependency node_modules\@img\sharp-wasm32
npm verbose reify failed optional dependency node_modules\@emnapi\runtime 
npm verbose reify failed optional dependency node_modules\tslib
npm verbose reify failed optional dependency node_modules\@img\sharp-linuxmusl-x64
npm verbose reify failed optional dependency node_modules\@img\sharp-linuxmusl-arm64
npm verbose reify failed optional dependency node_modules\@img\sharp-linux-x64
npm verbose reify failed optional dependency node_modules\@img\sharp-linux-s390x
npm verbose reify failed optional dependency node_modules\@img\sharp-linux-arm64
npm verbose reify failed optional dependency node_modules\@img\sharp-linux-arm
npm verbose reify failed optional dependency node_modules\@img\sharp-libvips-linuxmusl-x64
npm verbose reify failed optional dependency node_modules\@img\sharp-libvips-linuxmusl-arm64
npm verbose reify failed optional dependency node_modules\@img\sharp-libvips-linux-x64
npm verbose reify failed optional dependency node_modules\@img\sharp-libvips-linux-s390x
npm verbose reify failed optional dependency node_modules\@img\sharp-libvips-linux-arm64
npm verbose reify failed optional dependency node_modules\@img\sharp-libvips-linux-arm
npm verbose reify failed optional dependency node_modules\@img\sharp-libvips-darwin-x64
npm verbose reify failed optional dependency node_modules\@img\sharp-libvips-darwin-arm64
npm verbose reify failed optional dependency node_modules\@img\sharp-darwin-x64
npm verbose reify failed optional dependency node_modules\@img\sharp-darwin-arm64
npm http fetch GET 200 https://registry.npmjs.org/color-string/-/color-string-1.9.1.tgz 70ms (cache miss)     
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle/-/simple-swizzle-0.2.2.tgz 74ms (cache miss) 
npm http fetch GET 200 https://registry.npmjs.org/color/-/color-4.2.3.tgz 73ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc/-/detect-libc-2.0.3.tgz 91ms (cache miss)       
npm http fetch GET 200 https://registry.npmjs.org/tslib/-/tslib-2.6.3.tgz 102ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.3.2.tgz 104ms (cache miss)      
npm http fetch GET 200 https://registry.npmjs.org/sharp/-/sharp-0.33.4.tgz 124ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@emnapi/runtime/-/runtime-1.2.0.tgz 149ms (cache miss)      
npm info run sharp@0.33.4 install node_modules/sharp node install/check

> sharp@0.33.4 install
> node install/check

npm info run sharp@0.33.4 install { code: 0, signal: null }

added 9 packages in 3s

1 package is looking for funding
  run `npm fund` for details
npm verbose cwd C:\Users\wojte\Projekty\Rewardo\foo
npm verbose os Windows_NT 10.0.26100
npm verbose node v22.3.0
npm verbose npm  v10.8.1
npm verbose exit 0
npm info ok
</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

npm error code ENOENT
npm error syscall lstat
npm error path C:\Users\wojte\AppData\Roaming\npm
npm error errno -4058
npm error enoent ENOENT: no such file or directory, lstat 'C:\Users\wojte\AppData\Roaming\npm'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: C:\Users\wojte\AppData\Local\npm-cache\_logs\2024-06-25T13_34_49_248Z-debug-0.log

**Comment by lovell** [comment]
I've moved this issue to the sharp-libvips repo and tagged as a future possible enhancement as the work for this will start here.

There used to be partial support before https://github.com/lovell/sharp/issues/3750 - demand for Windows ARM was very, very low at the time (around 1 download per day).

This will probably be dependent on https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/

> "We expect to begin offering Arm runners for open source projects by the end of the year."

**Comment by alexfacciorusso** [comment]
Hello, arm64 needed here if possible too. Just adding weight as I read the demand is low, when lots of Copilot+ computers are bought every day right now. I believe now is starting getting a bit more relevant!

**Comment by knd775** [comment]
Also worth noting that windows arm64 runners went GA in September https://github.blog/changelog/2024-09-03-github-actions-arm64-linux-and-windows-runners-are-now-generally-available/

**Comment by lovell** [comment]
@knd775 Sadly it's only for paying customers: "Arm64 runners are available to customers on our Team and Enterprise Cloud plans."

**Comment by SuavePirate** [comment]
Following up here as another person who would really love a win-arm64 build. Would it be possible to sponsor the runner or some other way to compile for win-arm64 we could support while we wait for Github to open up the runners for OSS? @lovell

**Comment by radud** [comment]
hi @lovell thank you for this awesome library. On arm, can we compile ourself? Is it a big effort to compile locally?

**Comment by kleisauke** [comment]
The Windows ARM64 GitHub-hosted runners are now available for free in public repositories. :tada:
https://github.blog/changelog/2025-04-14-windows-arm64-hosted-runners-now-available-in-public-preview/
https://github.com/actions/partner-runner-images/blob/main/images/arm-windows-11-image.md

**Comment by dennisameling** [comment]
This should help to get another piece of the puzzle released: https://github.com/lovell/sharp-libvips/pull/272

**Comment by lovell** [comment]
https://www.npmjs.com/package/@img/sharp-libvips-win32-arm64 is now available and there's a work-in-progress PR to integrate this with sharp at https://github.com/lovell/sharp/pull/4375

**Comment by lovell** [comment]
A release candidate is now available for anyone that would like to test this:
```
npm install sharp@0.34.2-rc.0
```

**Comment by lovell** [comment]
Please can someone with access to a physical Windows AMR64 device verify that the release candidate is working for them. I'd like some confirmation we're good to go for a full release, thank you.

**Comment by dennisameling** [comment]
Can confirm this is working as expected with `sharp@0.34.2-rc.0` on a Windows ARM64 machine with this minimal code:

![image](https://github.com/user-attachments/assets/4e9f37c8-a310-4f3a-bba9-2c3fa20eeae9)

The `sample.webp` file is created correctly. Thanks!! 🎉

**Comment by lovell** [comment]
@dennisameling Brilliant, thank you very much for testing this.

**Comment by kleisauke** [comment]
I also confirm v0.34.2-rc.0 works great on my Raspberry Pi 4B with Windows 10 ARM64!
<details>
  <summary>Details</summary>

```console
$ npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) arm64 BCM2711 (ARM Cortex-A72)
    Memory: 1.41 GB / 3.86 GB
  Binaries:
    Node: 22.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    sharp: ^0.34.2-rc.0 => 0.34.2-rc.0

$ irm https://storage.googleapis.com/downloads.webmproject.org/webp/images/dancing_banana2.lossless.webp -OutFile banana.webp
$ node -p "require('sharp')('banana.webp', { animated: true }).resize(128).toFile('x.gif')"
Promise {
  {
    format: 'gif',
    width: 128,
    height: 1088,
    channels: 4,
    premultiplied: true,
    pageHeight: 136,
    pages: 8,
    size: 26018
  }
}
$ cd ../sharp-main
$ npm install
$ npm run test-unit
<snip />

  1718 passing (4m)
  4 pending
```


</details>

Though, I had to disable the [AVIF save tests](https://github.com/lovell/sharp/blob/v0.34.1/test/unit/avif.js#L47-L161) due to a `STATUS_ILLEGAL_INSTRUCTION` (`0xc000001d`) crash:
```console
$ node -p "require('sharp')('banana.webp', { animated: true }).resize(128).toFile('x.avif')"
$ CertUtil /error $LastExitCode
0xc000001d (NT: 0xc000001d STATUS_ILLEGAL_INSTRUCTION) -- 3221225501 (-1073741795)
Error message text: {EXCEPTION}
Illegal Instruction
An attempt was made to execute an illegal instruction.
CertUtil: -error command completed successfully.
```

I'll investigate further, but this might be due to the CPU used on this system (Raspberry Pi's aren't ideal for testing).

@dennisameling Can you confirm if AVIF saving works on your end?

**Comment by kleisauke** [comment]
It looks like the Neon dot-product CPU instructions are mandatory for AVIF save.
```console
(1404.1544): Illegal instruction - code c000001d (first chance)
(1404.1544): Illegal instruction - code c000001d (!!! second chance !!!)
libvips_42!variance_8xh_neon_dotprod+0x50 [inlined in libvips_42!aom_variance8x8_neon_dotprod+0x50]:
00007ffb`0163ded8 6e8294c0 udot        v0.4s,v6.16b,v2.16b
```

Unfortunately, the `AOM_SIMD_CAPS` and `AOM_SIMD_CAPS_MASK` environment variables have no effect when aom was built with `-DCONFIG_RUNTIME_CPU_DETECT=0`, see for example:
https://aomedia.googlesource.com/aom/+/refs/tags/v3.12.1/aom_ports/aarch64_cpudetect.c#25

Note to self: remove [this line](https://github.com/libvips/build-win64-mxe/blob/28422f2183aa2a376edf927eb3ce86ed1084a9b9/build/aom.mk#L24) once issue https://github.com/llvm/llvm-project/issues/80009 is fixed, since we likely don't want to raise the minimum required CPU to one that supports SVE instructions.

**Comment by wojtekmaj** [comment]
I did several more tests on Snapdragon X Plus and Snapdragon X Elite. All succeeded :)

**Comment by lovell** [comment]
v0.34.2 now available with *experimental* prebuilt binaries for Windows ARM64 - thanks all for your help testing this.
