### ISSUE TITLE
#14 is still an issue

### ISSUE THREAD

**Issue by monokrome** [lovell/sharp-libvips#47]
https://github.com/lovell/sharp-libvips/issues/14 was locked from commenting for no apparent reason, but the issue occurs on brand new macos machines with XCode & Homebrew installed.

```
bstoner@octave % (master) npm install
> sharp@0.22.1 install /Users/bstoner/Projects/github.com/FindOctave/cortex/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node i
nstall/dll-copy)
info sharp Using cached /Users/bstoner/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.4.0 runtime=node arch=x64 libc=
platform=darwin)
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc:130:19: error: no matching member function for call to 'Set'
        channels->Set(i, channelStat);
        ~~~~~~~~~~^~~
/Users/bstoner/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function
      not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/bstoner/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function
      not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
1 error generated.
make: *** [Release/obj.target/sharp/src/stats.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib
/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/Cellar/node/14.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modu
les/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bstoner/Projects/github.com/FindOctave/cortex/node_modules/sharp
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN angular-estree-parser@1.1.5 requires a peer of @angular/compiler@^6.0.0 || ^7.0.0 but none
is installed. You must install peer dependencies yourself.
npm WARN babel-eslint@10.0.1 requires a peer of eslint@>= 4.12.1 but none is installed. You must ins
tall peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed.
You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >=
3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none
 is installed. You must install peer dependencies yourself.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install)
|| (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bstoner/.npm/_logs/2020-07-02T18_58_04_711Z-debug.log
```

Installing libvips through Homebrew doesn't fix it, but deleting the `.npm/_libvips` cache leads to this:

```
bstoner@octave % (master) npm install sharp@0.25.4

> sharp@0.25.4 install /Users/bstoner/Projects/github.com/FindOctave/cortex/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Detected globally-installed libvips v8.9.2
info sharp Building from source via node-gyp
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:18:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:276:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/climits:41:
/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0/install-tools/include/limits.h:34:10: fatal error:
      'syslimits.h' file not found
#include "syslimits.h"
         ^~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/Cellar/node/14.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bstoner/Projects/github.com/FindOctave/cortex/node_modules/sharp
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN angular-estree-parser@1.1.5 requires a peer of @angular/compiler@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-eslint@10.0.1 requires a peer of eslint@>= 4.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.25.4 install: `(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.25.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bstoner/.npm/_logs/2020-07-02T19_25_23_537Z-debug.log
```

**EDIT:** I got around this via `brew install libvips` and adding this to my ZSHRC:

```sh
PKG_CONFIG_PATH=${PKG_CONFIG_PATH:-""}
if [[ -d /usr/local/ ]]; then
  local_pkgconfig_paths=(/usr/local/opt/*/lib/pkgconfig(N))
  for pkg_config_path in ${local_pkgconfig_paths[@]}; do PKG_CONFIG_PATH="${PKG_CONFIG_PATH[@]}:${pkg_config_path}"; done
fi
export PKG_CONFIG_PATH
```

**Comment by lovell** [comment]
Hi, the first log looks like an attempt to install sharp v0.22.1, which does not support Node.js 14, hence the following output:

> sharp@0.22.1 install /Users/bstoner/Projects/github.com/FindOctave/cortex/node_modules/sharp
> No prebuilt binaries found (target=14.4.0 runtime=node arch=x64 libc= platform=darwin)

The second log looks like an attempt to install sharp v0.25.4 where a global version of libvips has been made available, so sharp must be built from source, hence the following output:

> sharp@0.25.4 install /Users/bstoner/Projects/github.com/FindOctave/cortex/node_modules/sharp
> sharp Detected globally-installed libvips v8.9.2
> sharp Building from source via node-gyp

However the machine this is running on appears to have two compilers and two sets of C++ header files (`/Library/Developer/...` is xcode/clang but `/usr/local/Cellar/gcc/...` is gcc) that are conflicting with each other.

> In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/climits:41:
> /usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0/install-tools/include/limits.h:34:10: fatal error:

If you want to use a globally-installed libvips with sharp, or just need a working C++ compiler, then you'll need to fix the conflict. Reinstalling xcode and/or running `brew update && brew upgrade` often fixes these kind of things.

(The previous issue #14 from 2018 you linked to related to a permissions problem on CentOS 7, which is unrelated to the problems you've run into.)

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
